apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-writer
  labels:
    app: log-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-writer
  template:
    metadata:
      name: log-writer
      labels:
        app: log-writer
    spec:
      containers:
        - name: log-writer
          image: nepjnq/log-writer:1.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      