apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:1.0
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8080"
      